# Generated by Django 2.2.3 on 2019-07-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdialog',
            name='ans',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
