# Generated by Django 2.2.3 on 2019-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_botdialog_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdialog',
            name='ans',
            field=models.TextField(verbose_name='Ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='botdialog',
            name='req',
            field=models.TextField(verbose_name='Вопрос пользователя'),
        ),
    ]
