# Generated by Django 2.2.3 on 2019-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20190706_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdialog',
            name='ans',
            field=models.TextField(verbose_name='Бот спрашивает'),
        ),
        migrations.AlterField(
            model_name='botdialog',
            name='req',
            field=models.TextField(verbose_name='Пользователь отвечает'),
        ),
    ]
