# Generated by Django 2.2.3 on 2019-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20190706_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botdialog',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='botdialog',
            name='req',
        ),
        migrations.AddField(
            model_name='botdialog',
            name='dialog',
            field=models.TextField(default='SULU', verbose_name='Кусок диалога'),
            preserve_default=False,
        ),
    ]
