# Generated by Django 2.2.3 on 2019-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20190706_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstfrase', models.IntegerField(verbose_name='id первой фразы')),
                ('secondfrase', models.IntegerField(verbose_name='id вторая фраза')),
                ('balls', models.IntegerField(verbose_name='Количество баллов')),
            ],
        ),
    ]
