# Generated by Django 2.2.3 on 2019-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_botdialog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('school', models.IntegerField(verbose_name='id учреждения')),
                ('duration', models.IntegerField(verbose_name='Длительность курса')),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField(verbose_name='Стоимость курса')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название учреждения')),
            ],
        ),
    ]
