# Generated by Django 2.2.3 on 2019-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_courses_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='rate_auditors',
            field=models.FloatField(default=5, verbose_name='Оценка аудиторами'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='rate_students',
            field=models.FloatField(default=5, verbose_name='Оценка студентами'),
            preserve_default=False,
        ),
    ]
