# Generated by Django 2.2.3 on 2019-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_chatbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot_user',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Е-маил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot_user',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Телефон пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot_user',
            name='age',
            field=models.IntegerField(default=None, verbose_name='Возраст'),
        ),
    ]
